version: "3"

services:
  web:
    build: ../PycharmProjects/Projeto-Back-End/
    command:   sh -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
       - /usr/src/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
  client:
    build: ../projeto_front_end
    volumes:
      - ../projeto_front_end:/app
      - ../../app/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

    depends_on:
      - "web"
    command: npm start
